apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadkspc7434-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadkspc7434-tenant-component
    app.kubernetes.io/part-of: loadkspc7434-tenant-app
  name: loadkspc7434-tenant-component
  namespace: loadkspc7434-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadkspc7434-tenant-component
    weight: null
status: {}
